#!/bin/bash
set -x
set -e
set -o pipefail

/opt/python/3.10.13/bin/python3.10 /opt/The-Minecraft-Overviewer/overviewer.py -p 6 --genpoi --config=config.py

rm -r "${OVERVIEWER_OUTPUT_DIRECTORY}/custom-icons"
mkdir "${OVERVIEWER_OUTPUT_DIRECTORY}/custom-icons"
cp -r icons/* "${OVERVIEWER_OUTPUT_DIRECTORY}/custom-icons/"
